//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusStore.PairIntegration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PairIntegration.IPairIntegration")]
    public interface IPairIntegration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPairIntegration/Add", ReplyAction="http://tempuri.org/IPairIntegration/AddResponse")]
        PairIntegrationService.Pair Add(PairIntegrationService.Pair p1, PairIntegrationService.Pair p2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPairIntegration/Add", ReplyAction="http://tempuri.org/IPairIntegration/AddResponse")]
        System.Threading.Tasks.Task<PairIntegrationService.Pair> AddAsync(PairIntegrationService.Pair p1, PairIntegrationService.Pair p2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPairIntegration/Substract", ReplyAction="http://tempuri.org/IPairIntegration/SubstractResponse")]
        PairIntegrationService.Pair Substract(PairIntegrationService.Pair p1, PairIntegrationService.Pair p2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPairIntegration/Substract", ReplyAction="http://tempuri.org/IPairIntegration/SubstractResponse")]
        System.Threading.Tasks.Task<PairIntegrationService.Pair> SubstractAsync(PairIntegrationService.Pair p1, PairIntegrationService.Pair p2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPairIntegrationChannel : MusStore.PairIntegration.IPairIntegration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PairIntegrationClient : System.ServiceModel.ClientBase<MusStore.PairIntegration.IPairIntegration>, MusStore.PairIntegration.IPairIntegration {
        
        public PairIntegrationClient() {
        }
        
        public PairIntegrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PairIntegrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PairIntegrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PairIntegrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PairIntegrationService.Pair Add(PairIntegrationService.Pair p1, PairIntegrationService.Pair p2) {
            return base.Channel.Add(p1, p2);
        }
        
        public System.Threading.Tasks.Task<PairIntegrationService.Pair> AddAsync(PairIntegrationService.Pair p1, PairIntegrationService.Pair p2) {
            return base.Channel.AddAsync(p1, p2);
        }
        
        public PairIntegrationService.Pair Substract(PairIntegrationService.Pair p1, PairIntegrationService.Pair p2) {
            return base.Channel.Substract(p1, p2);
        }
        
        public System.Threading.Tasks.Task<PairIntegrationService.Pair> SubstractAsync(PairIntegrationService.Pair p1, PairIntegrationService.Pair p2) {
            return base.Channel.SubstractAsync(p1, p2);
        }
    }
}
