// <auto-generated />
namespace EF.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TopicColumnsDefaultValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TopicColumnsDefaultValues));
        
        string IMigrationMetadata.Id
        {
            get { return "201512300054167_TopicColumnsDefaultValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
